settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api-mt # unique identifier
    name: API.Mt
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.mt/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: api-mw # unique identifier
    name: API.mw
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.mw' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
    
  - id: api-cf # unique identifier
    name: API.cf
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.cf/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: egraph
    name: eGra.ph
#     description: 'Built for anything connected to the Internet.'
    url: 'https://egra.ph'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: actions-dev
    name: Actions.Dev
    url: 'https://actions.dev'
    method: GET
    expectStatus: 200
    
    
  - id: caching
    name: Cach.ng
    url: 'https://cach.ng/api/graphql'
    method: GET
    expectStatus: 200
    
    
  - id: caching59
    name: Cach.ng @ 59s
    url: 'https://cach.ng/api/graphql59'
    method: GET
    expectStatus: 200
    
    
  - id: hosts-cdn
    name: Graph CDN
    url: 'https://saas.graphcdn.app/?query={queryDomain{name}}'
    method: GET
    expectStatus: 200
    
  - id: hosts
    name: GCP US Central
    url: 'https://saas.us-central1.gcp.cloud.dgraph.io/graphql?query={queryDomain{name}}'
    method: GET
    expectStatus: 200
    
    
  - id: ai-co
    name: aï.co
    url: 'https://xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
    
  - id: ai-co-http
    name: aï.co (no SSL)
    url: 'http://xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
  - id: ai-co-sub
    name: sub.aï.co
    url: 'https://sub.xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
  - id: saasdev
    name: SaaS.Dev
    url: 'https://saas.dev'
    method: GET
    expectStatus: 200 
    
    
    
  - id: kvapi-a
    name: KV API
    url: 'https://xn--ap-ipa.ws/kv/SaaS'
    method: GET
    expectStatus: 200 
    
        
  - id: kvapihttp-a
    name: KV API (HTTP)
    url: 'http://xn--ap-ipa.ws/kv/API'
    method: GET
    expectStatus: 200 
    
    
        
  - id: kvapihttp2
    name: KV API Host 1 (HTTP)
    url: 'http://xn--a-nga.co/kv/Graph'
    method: GET
    expectStatus: 200 
    
    
        
  - id: kvapihttp3
    name: KV API Host 2 (HTTP)
    url: 'http://xn--ap-ipa.ws/kv/Graph'
    method: GET
    expectStatus: 200 
    
    
    
        
  - id: kvapihttp4
    name: KV API Same Host 2 (HTTP)
    url: 'http://xn--ap-ipa.ws/kv/Graph'
    method: GET
    expectStatus: 200 
    
    
        
  - id: cacheapi
    name: SWR Cache API Same
    url: 'https://xn--ap-ipa.com/cache'
    method: GET
    expectStatus: 200 
    
    
    
        
  - id: word
    name: Word
    url: 'https://api.cf/words/example'
    method: GET
    expectStatus: 200 
    
            
  - id: Symbols GH Pages
    name: symbols-gh-pages
    url: 'https://config.data.mt/data/symbols.json'
    method: GET
    expectStatus: 200 
    
    
            
  - id: Symbols GH Pages CF Proxy
    name: symbols-cf-gh-pages
    url: 'https://test.data.mt/data/symbols.json'
    method: GET
    expectStatus: 200 
    
    
            
  - id: Edge Function
    name: edge-function
    url: 'https://longtail.ventures/api'
    method: GET
    expectStatus: 200 
