settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api-mt # unique identifier
    name: API.Mt
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.mt/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
    
  - id: api-cf # unique identifier
    name: API.cf
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.cf/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: egraph
    name: eGra.ph
#     description: 'Built for anything connected to the Internet.'
    url: 'https://egra.ph'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: actions-dev
    name: Actions.Dev
    url: 'https://actions.dev'
    method: GET
    expectStatus: 200
    
    
  - id: caching
    name: Cach.ng
    url: 'https://cach.ng/api/graphql'
    method: GET
    expectStatus: 200
    
