settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: api-mt # unique identifier
    name: API.Mt
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.mt/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: api-mw # unique identifier
    name: API.mw
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.mw' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
    
  - id: api-cf # unique identifier
    name: API.cf
#     description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.cf/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: egraph
    name: eGra.ph
#     description: 'Built for anything connected to the Internet.'
    url: 'https://egra.ph'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: actions-dev
    name: Actions.Dev
    url: 'https://actions.dev'
    method: GET
    expectStatus: 200
    
    
  - id: caching
    name: Cach.ng
    url: 'https://cach.ng/api/graphql'
    method: GET
    expectStatus: 200
    
    
  - id: caching59
    name: Cach.ng @ 59s
    url: 'https://cach.ng/api/graphql59'
    method: GET
    expectStatus: 200
    
    
  - id: hosts-cdn
    name: Graph CDN
    url: 'https://saas.graphcdn.app/?query={queryDomain{name}}'
    method: GET
    expectStatus: 200
    
#   - id: hosts
#     name: GCP US Central
#     url: 'https://saas.us-central1.gcp.cloud.dgraph.io/graphql?query={queryDomain{name}}'
#     method: GET
#     expectStatus: 200
    
    
  - id: ai-co
    name: aï.co
    url: 'https://xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
    
  - id: ai-co-http
    name: aï.co (no SSL)
    url: 'http://xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
  - id: ai-co-sub
    name: sub.aï.co
    url: 'https://sub.xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
  - id: fast-co-sub
    name: sub.aï.co
    url: 'https://fast.xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
    
  - id: ai-co-again
    name: aï.co
    url: 'https://xn--a-nga.co/'
    method: GET
    expectStatus: 200 
    
    
  - id: ai-co-req
    name: aï.co req
    url: 'https://xn--a-nga.co/req'
    method: GET
    expectStatus: 200 
    
    
  - id: saasdev
    name: SaaS.Dev
    url: 'https://saas.dev'
    method: GET
    expectStatus: 200 
    
    
    
  - id: kvapi-a
    name: KV API
    url: 'https://xn--ap-ipa.ws/kv/SaaS'
    method: GET
    expectStatus: 200 
    
        
  - id: kvapihttp-a
    name: KV API (HTTP)
    url: 'http://xn--ap-ipa.ws/kv/API'
    method: GET
    expectStatus: 200 
    
    
        
  - id: kvapihttp2
    name: KV API Host 1 (HTTP)
    url: 'http://xn--a-nga.co/kv/Graph'
    method: GET
    expectStatus: 200 
    
    
        
  - id: kvapihttp3
    name: KV API Host 2 (HTTP)
    url: 'http://xn--ap-ipa.ws/kv/Graph'
    method: GET
    expectStatus: 200 
    
    
    
        
  - id: kvapihttp4
    name: KV API Same Host 2 (HTTP)
    url: 'http://xn--ap-ipa.ws/kv/Graph'
    method: GET
    expectStatus: 200 
    
    
        
  - id: cacheapi
    name: SWR Cache API Same
    url: 'https://xn--ap-ipa.com/cache'
    method: GET
    expectStatus: 200 
    
    
    
        
  - id: word
    name: Word
    url: 'https://api.cf/words/example'
    method: GET
    expectStatus: 200 
    
            
  - id: Symbols GH Pages
    name: symbols-gh-pages
    url: 'https://config.data.mt/data/symbols.json'
    method: GET
    expectStatus: 200 
    
    
            
  - id: Symbols GH Pages CF Proxy
    name: symbols-cf-gh-pages
    url: 'https://test.data.mt/data/symbols.json'
    method: GET
    expectStatus: 200 
    
    
            
  - id: Edge Function
    name: edge-function
    url: 'https://studio.sbs/api'
    method: GET
    expectStatus: 200 

            
  - id: Edge Function Subdomain
    name: edge-function-sub2
    url: 'https://test5.studio.sbs'
    method: GET
    expectStatus: 200 
    
    
  - id: DB
    name: db
    url: 'https://api.cfd/nocache/Domains'
    method: GET
    expectStatus: 200 
    
  - id: DB Cache SWR
    name: db-cache-swr
    url: 'https://api.cfd/swr/Domains'
    method: GET
    expectStatus: 200 
    
    
  - id: DB Cache
    name: db-cache
    url: 'https://api.cfd/db/Domains'
    method: GET
    expectStatus: 200 
    
  - id: SWR Cache
    name: swr-cache
    url: 'https://word.as/_next/data/rrSNvilhJGr9K_LbV2WP_/system.json'
    method: GET
    expectStatus: 200 
    
    
    
  - id: Static JSON
    name: static-json
    url: 'https://studio.sbs/symbols.json'
    method: GET
    expectStatus: 200 
    
    
    
    
  - id: CF Static JSON
    name: cf-static-json
    url: 'https://325438c6.portfolio-5rs.pages.dev/symbols.json'
    method: GET
    expectStatus: 200 
    
    
        
  - id: Test
    name: drivly-dev
    url: 'https://drivly.dev'
    method: GET
    expectStatus: 200 
    
    
        
  - id: Listing
    name: drivly-dev-listings
    url: 'https://drivly.dev/api/listings'
    method: GET
    expectStatus: 200 
    
    
        
  - id: Echo Repeat
    name: drivly-dev-echo
    url: 'https://drivly.dev'
    method: GET
    expectStatus: 200 
   
       
  - id: AirSync
    name: air-sync
    url: 'http://api.cfd/build/SaaS'
    method: GET
    expectStatus: 200 
    
  - id: Air
    name: air
    url: 'http://api.cfd/air/SaaS'
    method: GET
    expectStatus: 200 
        
  - id: Management
    name: mgmt
    url: 'https://api.mt'
    method: GET
    expectStatus: 200 
        
  - id: Actions
    name: actionst
    url: 'https://action.st'
    method: GET
    expectStatus: 200 
    
        
  - id: ActionsPost
    name: actionpost
    url: 'https://action.st/post/1'
    method: GET
    expectStatus: 200 
    
    
        
  - id: Counter
    name: counter
    url: 'https://api.countapi.xyz/hit/drive/visits'
    method: GET
    expectStatus: 200 
    
  - id: Counts
    name: counts
    url: 'https://counts.to/'
    method: GET
    expectStatus: 200 
    
    
  - id: CountsIP
    name: counts-ip
    url: 'http://counts.to/ip'
    method: GET
    expectStatus: 200 
    
  - id: CountsVal
    name: countsval
    url: 'https://counts.to/value'
    method: GET
    expectStatus: 200 
    
    
  - id: CountsIPVal
    name: counts-ip-val
    url: 'http://counts.to/ip/value'
    method: GET
    expectStatus: 200 

  - id: GCache
    name: gcache
    url: 'https://global-allowing-crane-30700.upstash.io/hget/school:1/type?_token=AnfsASQgMDVmMzExMTItMWIxYi00MGE1LWI2OTctN2YxNDMzNzAyNGM2eVcKYVRpCLpdX0vGiE3AIY3Q4znK7NObgS-sIf-POpM='
    method: GET
    expectStatus: 200 
    
    
